stages:
  - test
  - build

test:
  stage: test
  image: python:3.11-slim

  before_script:
    - pip install --no-cache-dir -r requirements.txt

  script:
    - python -m pytest


docker-build:
  stage: build
  image: docker:cli

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker build -t devops-prac:$CI_COMMIT_SHORT_SHA .
    - docker images